//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMgmt.UI.TaskMaterialUsageServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaskMaterialUsageServiceRef.ITaskMaterialUsageService")]
    public interface ITaskMaterialUsageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskMaterialUsageService/GetTaskMaterialUsages", ReplyAction="http://tempuri.org/ITaskMaterialUsageService/GetTaskMaterialUsagesResponse")]
        TaskMgmt.Model.TaskMaterialUsage[] GetTaskMaterialUsages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskMaterialUsageService/GetTaskMaterialUsages", ReplyAction="http://tempuri.org/ITaskMaterialUsageService/GetTaskMaterialUsagesResponse")]
        System.Threading.Tasks.Task<TaskMgmt.Model.TaskMaterialUsage[]> GetTaskMaterialUsagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskMaterialUsageService/GetTaskMaterialUsageByTaskId", ReplyAction="http://tempuri.org/ITaskMaterialUsageService/GetTaskMaterialUsageByTaskIdResponse" +
            "")]
        TaskMgmt.Model.TaskMaterialUsage GetTaskMaterialUsageByTaskId(string taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskMaterialUsageService/GetTaskMaterialUsageByTaskId", ReplyAction="http://tempuri.org/ITaskMaterialUsageService/GetTaskMaterialUsageByTaskIdResponse" +
            "")]
        System.Threading.Tasks.Task<TaskMgmt.Model.TaskMaterialUsage> GetTaskMaterialUsageByTaskIdAsync(string taskId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskMaterialUsageService/AddTaskMaterialUsage", ReplyAction="http://tempuri.org/ITaskMaterialUsageService/AddTaskMaterialUsageResponse")]
        void AddTaskMaterialUsage(TaskMgmt.Model.TaskMaterialUsage taskMaterialUsage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskMaterialUsageService/AddTaskMaterialUsage", ReplyAction="http://tempuri.org/ITaskMaterialUsageService/AddTaskMaterialUsageResponse")]
        System.Threading.Tasks.Task AddTaskMaterialUsageAsync(TaskMgmt.Model.TaskMaterialUsage taskMaterialUsage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskMaterialUsageService/UpdateTaskMaterialUsage", ReplyAction="http://tempuri.org/ITaskMaterialUsageService/UpdateTaskMaterialUsageResponse")]
        void UpdateTaskMaterialUsage(TaskMgmt.Model.TaskMaterialUsage taskMaterialUsage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskMaterialUsageService/UpdateTaskMaterialUsage", ReplyAction="http://tempuri.org/ITaskMaterialUsageService/UpdateTaskMaterialUsageResponse")]
        System.Threading.Tasks.Task UpdateTaskMaterialUsageAsync(TaskMgmt.Model.TaskMaterialUsage taskMaterialUsage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskMaterialUsageService/DeleteTaskMaterialUsage", ReplyAction="http://tempuri.org/ITaskMaterialUsageService/DeleteTaskMaterialUsageResponse")]
        void DeleteTaskMaterialUsage(string taskId, string materialId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskMaterialUsageService/DeleteTaskMaterialUsage", ReplyAction="http://tempuri.org/ITaskMaterialUsageService/DeleteTaskMaterialUsageResponse")]
        System.Threading.Tasks.Task DeleteTaskMaterialUsageAsync(string taskId, string materialId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskMaterialUsageServiceChannel : TaskMgmt.UI.TaskMaterialUsageServiceRef.ITaskMaterialUsageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskMaterialUsageServiceClient : System.ServiceModel.ClientBase<TaskMgmt.UI.TaskMaterialUsageServiceRef.ITaskMaterialUsageService>, TaskMgmt.UI.TaskMaterialUsageServiceRef.ITaskMaterialUsageService {
        
        public TaskMaterialUsageServiceClient() {
        }
        
        public TaskMaterialUsageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskMaterialUsageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskMaterialUsageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskMaterialUsageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TaskMgmt.Model.TaskMaterialUsage[] GetTaskMaterialUsages() {
            return base.Channel.GetTaskMaterialUsages();
        }
        
        public System.Threading.Tasks.Task<TaskMgmt.Model.TaskMaterialUsage[]> GetTaskMaterialUsagesAsync() {
            return base.Channel.GetTaskMaterialUsagesAsync();
        }
        
        public TaskMgmt.Model.TaskMaterialUsage GetTaskMaterialUsageByTaskId(string taskId) {
            return base.Channel.GetTaskMaterialUsageByTaskId(taskId);
        }
        
        public System.Threading.Tasks.Task<TaskMgmt.Model.TaskMaterialUsage> GetTaskMaterialUsageByTaskIdAsync(string taskId) {
            return base.Channel.GetTaskMaterialUsageByTaskIdAsync(taskId);
        }
        
        public void AddTaskMaterialUsage(TaskMgmt.Model.TaskMaterialUsage taskMaterialUsage) {
            base.Channel.AddTaskMaterialUsage(taskMaterialUsage);
        }
        
        public System.Threading.Tasks.Task AddTaskMaterialUsageAsync(TaskMgmt.Model.TaskMaterialUsage taskMaterialUsage) {
            return base.Channel.AddTaskMaterialUsageAsync(taskMaterialUsage);
        }
        
        public void UpdateTaskMaterialUsage(TaskMgmt.Model.TaskMaterialUsage taskMaterialUsage) {
            base.Channel.UpdateTaskMaterialUsage(taskMaterialUsage);
        }
        
        public System.Threading.Tasks.Task UpdateTaskMaterialUsageAsync(TaskMgmt.Model.TaskMaterialUsage taskMaterialUsage) {
            return base.Channel.UpdateTaskMaterialUsageAsync(taskMaterialUsage);
        }
        
        public void DeleteTaskMaterialUsage(string taskId, string materialId) {
            base.Channel.DeleteTaskMaterialUsage(taskId, materialId);
        }
        
        public System.Threading.Tasks.Task DeleteTaskMaterialUsageAsync(string taskId, string materialId) {
            return base.Channel.DeleteTaskMaterialUsageAsync(taskId, materialId);
        }
    }
}
